var npcInstincts = [
  "Avenge",
  "Spread the good word",
  "Reunite with a loved one",
  "Make money",
  "Make amends",
  "Explore a mysterious place",
  "Uncover a hidden truth",
  "Locate a lost thing",
  "Kill a hated foe",
  "Conquer a faraway land",
  "Cure an illness",
  "Craft a masterwork something",
  "Survive one more day",
  "Earn affection",
  "Prove a point",
  "Be smarter, faster, or stronger",
  "Heal an old wound",
  "Extinguish an evil forever",
  "Hide from a shameful fact",
  "Evangelize",
  "Spread suffering",
  "Prove worth",
  "Rise in rank",
  "Be praised",
  "Discover the truth",
  "Make good on a bet",
  "Get out of an obligation",
  "Convince someone to do their dirty work",
  "Steal something valuable",
  "Overcome a bad habit",
  "Commit an atrocity",
  "Earn fame/renown",
  "Accumulate power",
  "Save someone from a monstrosity",
  "Teach",
  "Settle down",
  "Get one more haul",
  "Preserve the law",
  "Discover",
  "Devour",
  "Restore the family name",
  "Live a quiet life",
  "Help others",
  "Atone",
  "Prove their worth",
  "Gain honor",
  "Expand their land",
  "Gain a title",
  "Retreat from society",
  "Escape",
  "Party",
  "Return home",
  "Serve",
  "Reclaim what was taken",
  "Do what must be done",
  "Be a champion",
  "Avoid notice",
  "Help a family member",
  "Perfect a skill",
  "Travel",
  "Overcome a disadvantage",
  "Play the game",
  "Establish a dynasty",
  "Improve the realm",
  "Retire",
  "Recover a lost memory",
  "Do battle",
  "Become a terror to criminals",
  "Raise dragons",
  "Live up to expectations",
  "Become someone else",
  "Do the impossible",
  "Become immortalized in song",
  "Be forgotten",
  "Find true love",
  "Lose their mind",
  "Indulge",
  "Make the best of it",
  "Locate the one",
  "Destroy an artifact",
  "Show them all",
  "Bring about unending summer or winter",
  "Fly",
  "Find the six-fingered man",
  "Wake the slumbering ancients",
  "Entertain",
  "Follow orders",
  "Die gloriously",
  "Be careful",
  "Show kindness",
  "Not screw it all up",
  "Uncover the past",
  "Go where no one has gone before",
  "Do good",
  "Become a beast",
  "Spill blood",
  "Live forever",
  "Hunt the most dangerous prey",
  "Hate",
  "Run away"
];

var npcKnacks = [
  "Criminal connections",
  "Muscle",
  "Skill with a specific weapon",
  "Hedge wizardry",
  "Comprehensive local knowledge",
  "Noble blood",
  "One-of-a-kind item",
  "Special destiny",
  "Unique perspective",
  "Hidden knowledge",
  "Magical awareness",
  "Abnormal parentage",
  "Political leverage",
  "Tie to a monster",
  "A secret",
  "True love",
  "An innocent heart",
  "Plan for the perfect crime",
  "One-way ticket to paradise",
  "Mysterious ore",
  "Money, money, money",
  "Divine blessing",
  "Immunity from the law",
  "Prophecy",
  "Secret martial arts techniques",
  "Ring of power",
  "Much-needed bag of potatoes",
  "A heart",
  "Fortified position",
  "Lawmaking",
  "Tongues",
  "A discerning eye",
  "Endurance",
  "A safe place",
  "Visions",
  "A beautiful mind",
  "A clear voice",
  "Stunning looks",
  "A catchy tune",
  "An invention",
  "Baking",
  "Brewing",
  "Smelting",
  "Woodworking",
  "Writing",
  "Immunity to fire",
  "Cooking",
  "Storytelling",
  "Ratcatching",
  "Lying",
  "Utterly unremarkable",
  "Mind-bending sexiness",
  "Undefined coolness",
  "Knot-tying",
  "Wheels of steel",
  "A magic carpet",
  "Endless ideas",
  "Persistence",
  "Stockpiles of food",
  "A hidden path",
  "Piety",
  "Resistance to disease",
  "A library",
  "A silver tongue",
  "Bloodline",
  "An innate spell",
  "Balance",
  "Souls",
  "Speed",
  "Sense of right and wrong",
  "Certainty",
  "Eye for detail",
  "Heroic self-sacrifice",
  "Sense of direction",
  "A big idea",
  "A hidden entrance",
  "Love of someone powerful",
  "Unquestioning loyalty",
  "Exotic fruit",
  "Poison",
  "Perfect memory",
  "Language of normal animals",
  "Key to an important door",
  "Metalworking",
  "Mysterious benefactor/s",
  "Nerves of steel",
  "Bluffing",
  "A trained animal companion",
  "Long-lost sibling regained",
  "Arrow with your name on it",
  "A true name",
  "Luck",
  "Attention of supernatural powers-that-be",
  "Kindness",
  "Strange tattoos",
  "A majestic beard",
  "A strange book written in a strange language",
  "Power overwhelming",
  "Delusions of grandeur",
  "Wind at their back and a spring in their step"
];

function createNpc() {
  var instinct = npcInstincts[Math.floor(Math.random() * npcInstincts.length)];
  var knack = npcKnacks[Math.floor(Math.random() * npcKnacks.length)];
  console.log("instinct =>", instinct, "\n", "knack =>", knack);
}

createNpc();
